### ISSUE TITLE
v2.0.0-alpha.14 meta release ticket

### ISSUE THREAD

**Issue by lennartkoopmann** [nzymedefense/nzyme#1044]
* New mandatory tap configs:

```toml
[protocols.udp]
pipeline_size = 16384

[protocols.dns]
pipeline_size = 4096
entropy_zscore_threshold = 3.0

[protocols.ssh]
pipeline_size = 1024

[protocols.socks]
pipeline_size = 1024

[protocols.arp]
pipeline_size = 1024
```

* We are changing some database column types. The first launch may take a while if you have a lot of Ethernet data collected.
* Data now coming from Connect (removed `fetch_ouis` and GeoIp page)
